services:
  db:
    image: postgres
    container_name: PostgresDB
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .envDB
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .envADMIN
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: